-- BRIMMO — Migración inicial de las 16 propiedades reales
-- Generado desde el DATA del index.html. Corré esto UNA sola vez.
-- Idempotente por título en español + ciudad.

-- 1. Villa en Caacupé, zona urbana
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Villa', 'VENTA', 'Caacupé', 515000000, 'GS', 830, NULL, 2, NULL, 'jb6os04D16A', -25.3861, -57.1408, 'Villa en Caacupé, zona urbana', 'Villa à Caacupé, zone urbaine', 'Villa in Caacupé, urban area', 'Zona urbana', 'Zone urbaine', 'Urban area', 'Villa en un barrio residencial de Caacupé, con entorno tranquilo y todos los servicios a pocos minutos. El terreno de 830 m² está completamente cerrado y la casa cuenta con dos dormitorios, living luminoso y una amplia terraza para aprovechar el clima durante todo el año. Tiene reserva de agua instalada, vista despejada al verde y acceso cómodo en cualquier época.', 'Villa dans un quartier résidentiel de Caacupé, dans un environnement paisible avec tous les services à quelques minutes. Le terrain de 830 m² est entièrement clôturé et la maison compte deux chambres, un salon lumineux et une grande terrasse pour profiter du climat toute l''année. Réserve d''eau installée, vue dégagée sur la verdure et accès facile en toute saison.', 'Villa in a residential neighbourhood of Caacupé, in a quiet setting with every service a few minutes away. The 830 m² plot is fully fenced and the house has two bedrooms, a bright living room and a wide terrace to enjoy the climate year round. It has an installed water reserve, open views over greenery and easy access in any season.', '["Terreno cerrado","Living luminoso","Amplia terraza","Reserva de agua","Barrio tranquilo y seguro","Comercios y escuelas cerca"]'::jsonb, '["Terrain clôturé","Salon lumineux","Grande terrasse","Réserve d''eau","Quartier calme et sécurisé","Commerces et écoles à proximité"]'::jsonb, '["Fenced plot","Bright living room","Wide terrace","Water reserve","Quiet, secure neighbourhood","Shops and schools nearby"]'::jsonb, true, true, NULL, 10
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Villa en Caacupé, zona urbana' and city = 'Caacupé');

-- 2. Villa a 5 minutos de Caacupé
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Villa', 'VENTA', 'Caacupé', 890000000, 'GS', NULL, 220, NULL, NULL, 'wgp7iHkPP9g', -25.3861, -57.1408, 'Villa a 5 minutos de Caacupé', 'Villa à 5 minutes de Caacupé', 'Villa 5 minutes from Caacupé', 'A 5 minutos del centro', 'À 5 minutes du centre', '5 minutes from the centre', 'Villa de una sola planta de 220 m², a cinco minutos de Caacupé y a una hora y media de Asunción. Está a 50 metros de la ruta asfaltada, en una zona tranquila y segura.', 'Villa de plain-pied de 220 m², à cinq minutes de Caacupé et à une heure et demie d''Asunción. Elle se trouve à 50 mètres de la route asphaltée, dans une zone calme et sécurisée.', 'Single-storey villa of 220 m², five minutes from Caacupé and an hour and a half from Asunción. It sits 50 metres from the paved road, in a quiet and secure area.', '["Una sola planta","A 50 m de ruta asfaltada","Zona segura"]'::jsonb, '["De plain-pied","À 50 m de la route asphaltée","Zone sécurisée"]'::jsonb, '["Single storey","50 m from the paved road","Secure area"]'::jsonb, false, false, 'La portada de la web anterior la describe como «villa de lujo con piscina», pero el catálogo no menciona piscina. Confirmar antes de publicar.', 20
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Villa a 5 minutos de Caacupé' and city = 'Caacupé');

-- 3. Quinta de 1,6 hectáreas en Atyrá
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Quinta', 'VENTA', 'Atyrá', 292000000, 'GS', 16000, 80, 3, 1, '2pG6a87NuPk', -25.2686, -57.1736, 'Quinta de 1,6 hectáreas en Atyrá', 'Quinta de 1,6 hectare à Atyrá', '1.6-hectare country home in Atyrá', NULL, NULL, NULL, 'Quinta de 1,6 hectáreas en Atyrá, a 30 minutos de Caacupé y 60 km de Asunción. El terreno es plano, está completamente cerrado y cuenta con pozo de agua potable. Tiene una gran variedad de árboles frutales —cítricos, mango, banana, guayaba, cacao— y dos colmenas para producción artesanal de miel. La construcción principal, de 80 m², es a refaccionar: tres dormitorios de 8, 9 y 14 m², entrada y living de 15 m², baño de 3,20 m² y cocina exterior de 20 m².', 'Quinta de 1,6 hectare à Atyrá, à 30 minutes de Caacupé et 60 km d''Asunción. Le terrain est plat, entièrement clôturé et dispose d''un puits d''eau potable. Il compte de nombreux arbres fruitiers — citronniers, orangers, pamplemoussiers, manguiers, bananiers, goyaviers, cacaoyers — et deux ruches pour une production artisanale de miel. Le bâti principal, de 80 m², est à rénover : trois chambres de 8, 9 et 14 m², entrée et salon de 15 m², salle de bain de 3,20 m² et cuisine extérieure de 20 m².', 'A 1.6-hectare country property in Atyrá, 30 minutes from Caacupé and 60 km from Asunción. The land is flat, fully fenced and has a drinking-water well. It holds a wide range of fruit trees — lemon, orange, grapefruit, mango, banana, guava, cacao — and two beehives for small-scale honey production. The main 80 m² building needs renovation: three bedrooms of 8, 9 and 14 m², a 15 m² entrance and living room, a 3.20 m² bathroom and a 20 m² outdoor kitchen.', '["Terreno plano y cerrado","Pozo de agua potable","Árboles frutales variados","Dos colmenas","Cocina exterior de 20 m²","Construcción a refaccionar"]'::jsonb, '["Terrain plat et clôturé","Puits d''eau potable","Nombreux arbres fruitiers","Deux ruches","Cuisine extérieure de 20 m²","Bâti à rénover"]'::jsonb, '["Flat, fenced land","Drinking-water well","Many fruit trees","Two beehives","20 m² outdoor kitchen","Building needs renovation"]'::jsonb, false, false, 'Conflicto de precio: la portada publica 37.600 USD y el catálogo 292.000.000 Gs (≈39.000 USD). Confirmar precio y moneda de referencia.', 30
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Quinta de 1,6 hectáreas en Atyrá' and city = 'Atyrá');

-- 4. Terreno de 4.300 m² dividido en cinco lotes
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Tobatí', 380000000, 'GS', 4300, NULL, NULL, NULL, 'aXHUcTVrz9Y', -25.2536, -57.0783, 'Terreno de 4.300 m² dividido en cinco lotes', 'Terrain de 4 300 m² divisé en cinq lots', '4,300 m² plot divided into five lots', 'Entre Tobatí y Caacupé', 'Entre Tobatí et Caacupé', 'Between Tobatí and Caacupé', 'Terreno de 4.300 m² dividido en cinco lotes, ubicado entre Tobatí y Caacupé. Tiene acceso directo desde la ruta y está listo para construir.', 'Terrain de 4 300 m² divisé en cinq lots, situé entre Tobatí et Caacupé. Accès direct depuis la route et prêt à construire.', 'A 4,300 m² plot divided into five lots, between Tobatí and Caacupé. Direct access from the road and ready to build on.', '["Dividido en 5 lotes","Acceso directo desde la ruta","Listo para construir"]'::jsonb, '["Divisé en 5 lots","Accès direct depuis la route","Prêt à construire"]'::jsonb, '["Divided into 5 lots","Direct road access","Ready to build"]'::jsonb, true, true, NULL, 40
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 4.300 m² dividido en cinco lotes' and city = 'Tobatí');

-- 5. Terreno de 9,45 hectáreas en Valenzuela
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Valenzuela', 147000, NULL, 94500, NULL, NULL, NULL, NULL, -25.6, -56.9833, 'Terreno de 9,45 hectáreas en Valenzuela', 'Terrain de 9,45 hectares à Valenzuela', '9.45-hectare plot in Valenzuela', 'A 39 km de Caacupé', 'À 39 km de Caacupé', '39 km from Caacupé', 'Terreno de 94.500 m² a 39 km de Caacupé. Es completamente plano y despejado, está limpio y listo para trabajar, y queda a solo 3 km de la ruta asfaltada. Un entorno tranquilo, apto para producción agrícola, ganadería, proyectos de autonomía o residencia de campo.', 'Terrain de 94 500 m² à 39 km de Caacupé. Entièrement plat et dégagé, propre et prêt à être exploité, à seulement 3 km d''une route asphaltée. Un cadre paisible, adapté à une production agricole, à l''élevage, à un projet d''autonomie ou à une résidence de campagne.', 'A 94,500 m² plot 39 km from Caacupé. Completely flat and clear, clean and ready to work, just 3 km from a paved road. A quiet setting suited to farming, livestock, a self-sufficiency project or a country residence.', '["Completamente plano y despejado","Limpio y listo para trabajar","A 3 km de ruta asfaltada","Apto para producción agrícola"]'::jsonb, '["Entièrement plat et dégagé","Propre et prêt à exploiter","À 3 km d''une route asphaltée","Adapté à la production agricole"]'::jsonb, '["Completely flat and clear","Clean and ready to work","3 km from a paved road","Suited to farming"]'::jsonb, false, false, 'El precio figura como «147 000» sin indicar moneda. Confirmar si son guaraníes, dólares o euros.', 50
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 9,45 hectáreas en Valenzuela' and city = 'Valenzuela');

-- 6. Terreno de 7,8 hectáreas sobre ruta Tobatí–Aguaity
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Tobatí', 150000, 'USD', 78000, NULL, NULL, NULL, NULL, -25.2536, -57.0783, 'Terreno de 7,8 hectáreas sobre ruta Tobatí–Aguaity', 'Terrain de 7,8 hectares sur la route Tobatí–Aguaity', '7.8-hectare plot on the Tobatí–Aguaity road', 'Aguaity', 'Aguaity', 'Aguaity', 'Propiedad rural de 7,8 hectáreas en una ubicación privilegiada de La Cordillera, a pocos minutos de Tobatí. Tiene 217 metros lineales de frente sobre la ruta asfaltada Tobatí–Aguaity y acceso directo al arroyo Ytú. El título y los impuestos están en regla, listos para transferencia, e incluye plano de mensura georreferenciado inscripto en el Servicio Nacional de Catastro. Apta para estancia, explotación agrícola, proyecto turístico, loteamiento o inversión.', 'Propriété rurale de 7,8 hectares dans un emplacement privilégié de La Cordillera, à quelques minutes de Tobatí. Elle bénéficie de 217 mètres linéaires de façade sur la route asphaltée Tobatí–Aguaity et d''un accès direct au ruisseau Ytú. Titre de propriété et taxes en règle, prêt pour le transfert, avec un plan de bornage géoréférencé enregistré auprès du Service national du cadastre. Idéale pour un domaine, une exploitation agricole, un projet touristique, un lotissement ou un investissement.', 'A 7.8-hectare rural property in a prime spot in La Cordillera, minutes from Tobatí. It has 217 linear metres of frontage on the paved Tobatí–Aguaity road and direct access to the Ytú stream. Title and taxes are in order and ready for transfer, and it includes a georeferenced survey plan registered with the National Cadastre Service. Suited to an estate, farming, a tourism project, a subdivision or an investment.', '["217 m de frente sobre ruta asfaltada","Acceso directo al arroyo Ytú","Título e impuestos en regla","Plano de mensura georreferenciado"]'::jsonb, '["217 m de façade sur route asphaltée","Accès direct au ruisseau Ytú","Titre et taxes en règle","Plan de bornage géoréférencé"]'::jsonb, '["217 m of paved-road frontage","Direct access to the Ytú stream","Title and taxes in order","Georeferenced survey plan"]'::jsonb, true, false, NULL, 60
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 7,8 hectáreas sobre ruta Tobatí–Aguaity' and city = 'Tobatí');

-- 7. Quinta de 2 hectáreas sobre la ruta de Atyrá
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Quinta', 'VENTA', 'Caacupé', 180000, 'USD', 20000, NULL, NULL, NULL, NULL, -25.3861, -57.1408, 'Quinta de 2 hectáreas sobre la ruta de Atyrá', 'Quinta de 2 hectares sur la route d''Atyrá', '2-hectare country home on the Atyrá road', 'Ruta de Atyrá', 'Route d''Atyrá', 'Atyrá road', 'Quinta a cinco minutos de Caacupé, sobre la ruta de Atyrá, en una zona tranquila y arbolada. La construcción principal es sólida y funcional, y el terreno es plano y de acceso fácil desde la ruta. Cuenta con quincho amplio con parrilla y piscina, con espacio suficiente para ampliar o desarrollar nuevas construcciones. Ideal para un proyecto ecoturístico, una residencia familiar o una casa de fin de semana.', 'Quinta à cinq minutes de Caacupé, sur la route d''Atyrá, dans une zone calme et verdoyante. La construction principale est solide et fonctionnelle, et le terrain est plat, d''accès facile depuis la route. Elle dispose d''un grand quincho avec barbecue et d''une piscine, avec assez d''espace pour agrandir ou développer d''autres constructions. Idéale pour un projet éco-touristique, une résidence familiale ou une maison de vacances.', 'A country property five minutes from Caacupé, on the Atyrá road, in a quiet, wooded area. The main building is solid and functional, and the land is flat with easy access from the road. It has a large covered barbecue area and a pool, with room to extend or add further buildings. Ideal for an eco-tourism project, a family home or a weekend house.', '["Quincho amplio con parrilla","Piscina","Terreno plano","Acceso directo desde la ruta","Espacio para ampliar"]'::jsonb, '["Grand quincho avec barbecue","Piscine","Terrain plat","Accès direct depuis la route","Espace pour agrandir"]'::jsonb, '["Large covered barbecue area","Swimming pool","Flat land","Direct road access","Room to extend"]'::jsonb, true, false, NULL, 70
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Quinta de 2 hectáreas sobre la ruta de Atyrá' and city = 'Caacupé');

-- 8. Propiedad de 5,7 hectáreas en Itacurubí
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Itacurubí de la Cordillera', 157000, NULL, 57000, NULL, NULL, NULL, NULL, -25.4833, -56.85, 'Propiedad de 5,7 hectáreas en Itacurubí', 'Propriété de 5,7 hectares à Itacurubí', '5.7-hectare property in Itacurubí', 'Camino Itacurubí–Isla Pucú', 'Chemin Itacurubí–Isla Pucú', 'Itacurubí–Isla Pucú road', 'Propiedad de 5,7 hectáreas completamente arbolada, sobre un camino de tierra con mantenimiento regular entre Itacurubí de la Cordillera y Santa Elena. Cuenta con conexión a electricidad trifásica y a la red de agua potable. Tiene cerca de mil pinos plantados hace 27 años, numerosos árboles nativos ya maduros y variedad de frutales, entre ellos alrededor de cien macadamias y cien mamones.', 'Propriété de 5,7 hectares entièrement boisée, sur un chemin non goudronné mais régulièrement entretenu entre Itacurubí de la Cordillera et Santa Elena. Elle bénéficie d''un raccordement à l''électricité triphasée et au réseau d''eau potable. Elle compte environ mille pins plantés il y a 27 ans, de nombreux arbres indigènes déjà matures et une variété d''arbres fruitiers, dont une centaine de macadamias et une centaine de papayers.', 'A fully wooded 5.7-hectare property on an unpaved but regularly maintained road between Itacurubí de la Cordillera and Santa Elena. It has three-phase electricity and a mains water connection. It holds around a thousand pines planted 27 years ago, many mature native trees and a range of fruit trees, including about a hundred macadamias and a hundred papayas.', '["Completamente arbolada","Electricidad trifásica","Red de agua potable","Cerca de mil pinos de 27 años","Frutales: macadamia y mamón"]'::jsonb, '["Entièrement boisée","Électricité triphasée","Réseau d''eau potable","Près de mille pins de 27 ans","Fruitiers : macadamia et papaye"]'::jsonb, '["Fully wooded","Three-phase electricity","Mains water","Around a thousand 27-year-old pines","Fruit trees: macadamia and papaya"]'::jsonb, false, false, 'El precio figura como «157 000» sin indicar moneda. Confirmar.', 80
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Propiedad de 5,7 hectáreas en Itacurubí' and city = 'Itacurubí de la Cordillera');

-- 9. Terreno de 2 hectáreas en las alturas de Atyrá
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Atyrá', 370000000, 'GS', 20000, NULL, NULL, NULL, NULL, -25.2686, -57.1736, 'Terreno de 2 hectáreas en las alturas de Atyrá', 'Terrain de 2 hectares sur les hauteurs d''Atyrá', '2-hectare plot in the hills of Atyrá', 'Zona alta', 'Zone haute', 'Upper area', 'Terreno en las alturas de Atyrá, una de las zonas más buscadas de La Cordillera, con entorno natural preservado y vista despejada. Mide 110 por 200 metros, tiene árboles frutales y cuenta con agua y electricidad a 300 metros. El acceso es por 1,2 km de camino de tierra.', 'Terrain sur les hauteurs d''Atyrá, l''une des zones les plus recherchées de La Cordillera, dans un environnement naturel préservé avec vue dégagée. Il mesure 110 sur 200 mètres, compte des arbres fruitiers et dispose de l''eau et de l''électricité à 300 mètres. L''accès se fait par 1,2 km de piste.', 'A plot in the hills of Atyrá, one of the most sought-after areas in La Cordillera, in a preserved natural setting with open views. It measures 110 by 200 metres, has fruit trees and water and electricity 300 metres away. Access is via 1.2 km of dirt track.', '["Árboles frutales","Vista despejada","Agua y electricidad a 300 m","Acceso por 1,2 km de camino"]'::jsonb, '["Arbres fruitiers","Vue dégagée","Eau et électricité à 300 m","Accès par 1,2 km de piste"]'::jsonb, '["Fruit trees","Open views","Water and power 300 m away","Access via 1.2 km track"]'::jsonb, false, false, 'La publicación lo describe como 2 hectáreas, pero las medidas declaradas (110 × 200 m) equivalen a 2,2 ha. Confirmar superficie real.', 90
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 2 hectáreas en las alturas de Atyrá' and city = 'Atyrá');

-- 10. Terreno de 2 hectáreas en Eusebio Ayala
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Eusebio Ayala', 210000000, 'GS', 20000, NULL, NULL, NULL, NULL, -25.3833, -56.9333, 'Terreno de 2 hectáreas en Eusebio Ayala', 'Terrain de 2 hectares à Eusebio Ayala', '2-hectare plot in Eusebio Ayala', NULL, NULL, NULL, 'Terreno de 2 hectáreas en Eusebio Ayala, con acceso fácil, electricidad y agua disponibles y servicios habilitados. Zona tranquila y segura, apta para construir una vivienda, desarrollar un proyecto o invertir en una región en crecimiento.', 'Terrain de 2 hectares à Eusebio Ayala, d''accès facile, avec électricité et eau disponibles et les services viabilisés. Zone calme et sécurisée, adaptée à la construction d''une résidence, au développement d''un projet ou à un investissement dans une région en pleine croissance.', 'A 2-hectare plot in Eusebio Ayala with easy access, electricity and water available and services connected. A quiet, secure area suited to building a home, developing a project or investing in a growing region.', '["Acceso fácil","Electricidad y agua disponibles","Terreno con servicios habilitados","Zona tranquila y segura"]'::jsonb, '["Accès facile","Électricité et eau disponibles","Terrain viabilisé","Zone calme et sécurisée"]'::jsonb, '["Easy access","Electricity and water available","Services connected","Quiet, secure area"]'::jsonb, true, false, NULL, 100
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 2 hectáreas en Eusebio Ayala' and city = 'Eusebio Ayala');

-- 11. Terreno de 5.440 m² en Cabañas
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Caacupé', 170000000, 'GS', 5440, NULL, NULL, NULL, NULL, -25.3861, -57.1408, 'Terreno de 5.440 m² en Cabañas', 'Terrain de 5 440 m² à Cabañas', '5,440 m² plot in Cabañas', 'Cabañas', 'Cabañas', 'Cabañas', 'Terreno baldío en Cabañas, a solo 2 km del centro de Caacupé, en un barrio tranquilo y buscado. Está en altura y ofrece una vista panorámica amplia.', 'Terrain nu à Cabañas, à seulement 2 km du centre de Caacupé, dans un quartier calme et recherché. Situé en hauteur, il offre une belle vue panoramique.', 'An empty plot in Cabañas, just 2 km from the centre of Caacupé, in a quiet, sought-after neighbourhood. It sits high up and offers wide panoramic views.', '["A 2 km del centro de Caacupé","Terreno en altura","Vista panorámica","Barrio tranquilo"]'::jsonb, '["À 2 km du centre de Caacupé","Terrain en hauteur","Vue panoramique","Quartier calme"]'::jsonb, '["2 km from central Caacupé","Elevated plot","Panoramic views","Quiet neighbourhood"]'::jsonb, false, false, 'La publicación indica 5.440 m² pero las medidas declaradas (144 × 37 m) dan 5.328 m². Confirmar cuál figura en el catastro.', 110
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 5.440 m² en Cabañas' and city = 'Caacupé');

-- 12. Rancho en Eusebio Ayala
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Rancho', 'VENTA', 'Eusebio Ayala', 840000000, 'GS', NULL, NULL, NULL, NULL, NULL, -25.3833, -56.9333, 'Rancho en Eusebio Ayala', 'Ranch à Eusebio Ayala', 'Ranch in Eusebio Ayala', 'A 20 km de Caacupé', 'À 20 km de Caacupé', '20 km from Caacupé', 'Propiedad a 20 km de Caacupé, junto a Eusebio Ayala, donde se encuentran todos los servicios esenciales: comercios, escuelas, centros de salud, restaurantes y estaciones de servicio. Tiene frente sobre ruta asfaltada, con acceso cómodo durante todo el año. Apta para un proyecto agrícola, un loteamiento, una residencia de campo, una inversión o un desarrollo turístico.', 'Propriété à 20 km de Caacupé, près d''Eusebio Ayala, où se trouvent tous les services essentiels : commerces, écoles, centres de santé, restaurants et stations-service. Elle dispose d''une façade sur route asphaltée, avec un accès facile toute l''année. Idéale pour un projet agricole, un lotissement, une résidence de campagne, un investissement ou un projet touristique.', 'A property 20 km from Caacupé, next to Eusebio Ayala, where all essential services are available: shops, schools, health centres, restaurants and petrol stations. It has frontage on a paved road with easy access year round. Suited to a farming project, a subdivision, a country residence, an investment or a tourism development.', '["Frente sobre ruta asfaltada","Acceso cómodo todo el año","Servicios esenciales cerca","Apto para proyecto agrícola o turístico"]'::jsonb, '["Façade sur route asphaltée","Accès facile toute l''année","Services essentiels à proximité","Adaptée à un projet agricole ou touristique"]'::jsonb, '["Paved-road frontage","Easy access year round","Essential services nearby","Suited to farming or tourism"]'::jsonb, false, false, 'El título indica 10 hectáreas y la descripción 9 hectáreas. Confirmar superficie según título de propiedad.', 120
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Rancho en Eusebio Ayala' and city = 'Eusebio Ayala');

-- 13. Terreno de 14 hectáreas en Ita Yvu Guasu
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Caacupé', 1470000000, 'GS', 140000, NULL, NULL, NULL, NULL, -25.3861, -57.1408, 'Terreno de 14 hectáreas en Ita Yvu Guasu', 'Terrain de 14 hectares à Ita Yvu Guasu', '14-hectare plot in Ita Yvu Guasu', 'Ita Yvu Guasu', 'Ita Yvu Guasu', 'Ita Yvu Guasu', 'Propiedad de 14 hectáreas a pocos minutos de Caacupé, con un arroyo natural que la atraviesa y cerca del 70% de vegetación natural entre arbustos y árboles. El acceso es cómodo todo el año, con 3 km de camino de tierra, y la ruta de acceso está en proceso de asfaltado. Es una zona valorada por las comunidades suiza y alemana. Apta para estancia privada, proyecto turístico o ecológico, granja autónoma, ganadería, agroforestería o loteamiento rural.', 'Propriété de 14 hectares à quelques minutes de Caacupé, traversée par un ruisseau naturel et couverte à près de 70 % de végétation naturelle, arbustes et arbres. L''accès est aisé toute l''année, avec 3 km de piste, et la route d''accès est en cours de bitumage. C''est un secteur apprécié des communautés suisse et allemande. Idéale pour un domaine privé, un projet touristique ou écologique, une ferme autonome, de l''élevage, de l''agroforesterie ou un lotissement rural.', 'A 14-hectare property minutes from Caacupé, crossed by a natural stream and around 70% covered in natural vegetation, shrubs and trees. Access is comfortable year round over 3 km of track, and the access road is being paved. The area is favoured by the Swiss and German communities. Suited to a private estate, a tourism or ecological project, a self-sufficient farm, livestock, agroforestry or a rural subdivision.', '["Arroyo natural que atraviesa la propiedad","70% de vegetación natural","A 3 km de camino de tierra","Ruta de acceso en proceso de asfaltado"]'::jsonb, '["Ruisseau naturel traversant la propriété","70 % de végétation naturelle","3 km de piste","Route d''accès en cours de bitumage"]'::jsonb, '["Natural stream crossing the land","70% natural vegetation","3 km of track","Access road being paved"]'::jsonb, false, false, 'Doble precio: 1.470.000.000 Gs y «~212.000» con la moneda ilegible en el original. Los dos valores no coinciden entre sí. Confirmar.', 130
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 14 hectáreas en Ita Yvu Guasu' and city = 'Caacupé');

-- 14. Terreno de 4.400 m² en Cabañas
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Terreno', 'VENTA', 'Caacupé', 357000000, 'GS', 4400, NULL, NULL, NULL, NULL, -25.3861, -57.1408, 'Terreno de 4.400 m² en Cabañas', 'Terrain de 4 400 m² à Cabañas', '4,400 m² plot in Cabañas', 'Cabañas', 'Cabañas', 'Cabañas', 'Terreno de 4.400 m² en Cabañas, a pocos minutos del centro de Caacupé. Está completamente cerrado con portón de acceso, cuenta con agua y electricidad, y queda a 700 metros de la ruta asfaltada, con comercio de cercanía y acceso cómodo todo el año. Ya tiene un pequeño galpón/establo en el terreno.', 'Terrain de 4 400 m² à Cabañas, à quelques minutes du centre de Caacupé. Entièrement clôturé avec portail d''accès, il dispose de l''eau et de l''électricité et se trouve à 700 mètres de la route asphaltée, avec commerce de proximité et un accès facile toute l''année. Un petit bâtiment/étable est déjà présent sur le terrain.', 'A 4,400 m² plot in Cabañas, minutes from the centre of Caacupé. Fully fenced with an access gate, it has water and electricity and sits 700 metres from the paved road, with a local shop nearby and easy access year round. A small shed/stable is already built on the land.', '["Completamente cerrado con portón","Agua y electricidad","A 700 m de ruta asfaltada","Galpón/establo ya construido"]'::jsonb, '["Entièrement clôturé avec portail","Eau et électricité","À 700 m de la route asphaltée","Petit bâtiment/étable déjà construit"]'::jsonb, '["Fully fenced with gate","Water and electricity","700 m from the paved road","Small shed/stable already built"]'::jsonb, true, false, NULL, 140
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Terreno de 4.400 m² en Cabañas' and city = 'Caacupé');

-- 15. Departamento en Asunción
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Departamento', 'VENTA', 'Asunción', NULL, NULL, NULL, NULL, NULL, NULL, NULL, -25.2637, -57.5759, 'Departamento en Asunción', 'Appartement à Asunción', 'Apartment in Asunción', NULL, NULL, NULL, '', '', '', '[]'::jsonb, '[]'::jsonb, '[]'::jsonb, false, false, 'La publicación original no incluye precio, superficie ni fotografías. Confirmar si sigue vigente.', 150
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Departamento en Asunción' and city = 'Asunción');

-- 16. Casa sobre terreno de 448 m² en Cabañas
insert into brimmo.propiedades (type, operation, city, price, currency, land, built, beds, baths, video_id, lat, lng, title_es, title_fr, title_en, zone_es, zone_fr, zone_en, desc_es, desc_fr, desc_en, features_es, features_fr, features_en, published, featured, pendiente, orden)
select 'Casa', 'VENTA', 'Caacupé', 39500, 'USD', 448, NULL, 2, 1, NULL, -25.3861, -57.1408, 'Casa sobre terreno de 448 m² en Cabañas', 'Maison sur terrain de 448 m² à Cabañas', 'House on a 448 m² plot in Cabañas', 'Cabañas', 'Cabañas', 'Cabañas', 'Casa en zona semiurbana de Cabañas, Caacupé, sobre un terreno de 448 m² completamente cerrado. Tiene dos dormitorios, living, baño y espacio de cocina. Está en buen estado general y admite trabajos menores de refacción. Los comercios quedan a menos de 500 metros.', 'Maison en zone semi-urbaine de Cabañas, Caacupé, sur un terrain de 448 m² entièrement clôturé. Elle compte deux chambres, un salon, une salle de bain et un espace cuisine. En bon état général, elle admet quelques petits travaux de rafraîchissement. Les commerces sont à moins de 500 mètres.', 'A house in the semi-urban area of Cabañas, Caacupé, on a fully fenced 448 m² plot. It has two bedrooms, a living room, a bathroom and a kitchen space. In good general condition, it would take some light refreshing. Shops are less than 500 metres away.', '["Terreno completamente cerrado","Living","Espacio de cocina","Zona semiurbana","Comercios a menos de 500 m"]'::jsonb, '["Terrain entièrement clôturé","Salon","Espace cuisine","Zone semi-urbaine","Commerces à moins de 500 m"]'::jsonb, '["Fully fenced plot","Living room","Kitchen space","Semi-urban area","Shops under 500 m away"]'::jsonb, false, false, 'Publicada solo en la portada de la web anterior, no en el catálogo. Confirmar vigencia y datos.', 160
where not exists (select 1 from brimmo.propiedades
                  where title_es = 'Casa sobre terreno de 448 m² en Cabañas' and city = 'Caacupé');

